conn = None
cursor = None
root = None
tree = None
tree_carrello = None  # legacy — unused after cart redesign
cart_frame = None     # inner frame of the scrollable cart, holds per-item cards
entry_nome = None
entry_quantita = None
entry_prezzo = None
entry_barcode = None
entry_ricerca = None
carrello = None
totale_var = None
